from __future__ import annotations

import datetime as dt
from typing import TYPE_CHECKING
from urllib.parse import urlsplit

from loguru import logger
from tortoise.connection import get_connection

if TYPE_CHECKING:
    from collections.abc import Mapping

    import discord

    from embed_fixer.cogs.fixer import Media


MESSAGE_ARCHIVE_SCHEMA = """
CREATE TABLE IF NOT EXISTS message
(
    channel_id TEXT NOT NULL,
    id TEXT NOT NULL,
    content TEXT NOT NULL,
    username TEXT NOT NULL,
    "timestamp" INTEGER NOT NULL DEFAULT (unixepoch()),
    CONSTRAINT message_pk PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS "message_id_IDX" ON "message" ("id");
CREATE TABLE IF NOT EXISTS embed
(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    message_id TEXT NOT NULL,
    title TEXT NOT NULL,
    url TEXT NOT NULL,
    author_icon_url TEXT,
    author_name TEXT,
    author_url TEXT,
    description TEXT NOT NULL,
    footer_icon_url TEXT,
    footer_text TEXT,
    image_url TEXT,
    image_proxy_url TEXT,
    "timestamp" TEXT NOT NULL,
    local_filename TEXT,
    orginal_url TEXT,
    is_downloaded INTEGER NOT NULL DEFAULT (0)
);
CREATE TABLE IF NOT EXISTS attachment
(
    id TEXT NOT NULL,
    message_id TEXT NOT NULL,
    "size" INTEGER NOT NULL,
    filename TEXT NOT NULL,
    url TEXT NOT NULL,
    ephemeral INTEGER NOT NULL,
    is_downloaded INTEGER NOT NULL DEFAULT (0),
    CONSTRAINT attachment_pk PRIMARY KEY (id)
);
"""

POSTGRES_MESSAGE_ARCHIVE_SCHEMA = """
CREATE TABLE IF NOT EXISTS message (
    id int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    channel_id int8 NOT NULL,
    "content" varchar(1024) NULL,
    username varchar(128) NULL,
    "timestamp" timestamp DEFAULT CURRENT_TIMESTAMP NULL,
    CONSTRAINT message_pk PRIMARY KEY (id)
);
CREATE TABLE IF NOT EXISTS embed (
    id int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    message_id int8 NOT NULL,
    title varchar(1024) NULL,
    url varchar(512) NULL,
    author_icon_url varchar(512) NULL,
    author_name varchar(128) NULL,
    author_url varchar(512) NULL,
    description varchar(512) NULL,
    footer_icon_url varchar(512) NULL,
    footer_text varchar(512) NULL,
    image_url varchar(512) NULL,
    image_proxy_url varchar(512) NULL,
    "timestamp" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
    embed_timestamp timestamp NULL,
    local_filename varchar(512) NULL,
    orginal_url varchar(512) NULL,
    is_downloaded boolean DEFAULT false NOT NULL,
    CONSTRAINT embed_pk PRIMARY KEY (id)
);
CREATE TABLE IF NOT EXISTS attachment (
    message_id int8 NOT NULL,
    "size" int4 NULL,
    filename varchar(512) NULL,
    url varchar(512) NULL,
    ephemeral int8 NULL,
    is_downloaded boolean DEFAULT false NOT NULL
);
"""


def _truncate(value: str | None, length: int) -> str | None:
    if value is None:
        return None
    return value[:length]


def _postgres_timestamp(value: dt.datetime | None) -> dt.datetime | None:
    if value is None:
        return None
    if value.tzinfo is None:
        return value
    return value.astimezone(dt.UTC).replace(tzinfo=None)


def _normalize_url_for_match(url: str | None) -> str:
    if not url:
        return ""

    try:
        parsed = urlsplit(url)
    except ValueError:
        return url.lower()

    hostname = (parsed.hostname or "").lower().removeprefix("www.")
    if hostname == "twitter.com":
        hostname = "x.com"

    path_parts = [part for part in parsed.path.split("/") if part]
    if hostname in {"x.com", "fixupx.com", "fxtwitter.com"} and "status" in path_parts:
        status_index = path_parts.index("status")
        if status_index + 1 < len(path_parts):
            return f"{hostname}/status/{path_parts[status_index + 1]}".lower()

    return f"{hostname}{parsed.path.rstrip('/')}".lower()


def _merge_processed_url(
    embed_rows: list[list[object | None]],
    *,
    original_url: str,
    processed_url: str,
    stored_original_url: str | None = None,
    original_url_index: int,
) -> bool:
    normalized_original_url = _normalize_url_for_match(original_url)
    for row in embed_rows:
        row_url = row[2]
        if (
            isinstance(row_url, str)
            and _normalize_url_for_match(row_url) == normalized_original_url
        ):
            row[2] = processed_url
            row[original_url_index] = (
                original_url if stored_original_url is None else stored_original_url
            )
            return True

    return False


def _set_original_url_for_processed_url(
    embed_rows: list[list[object | None]],
    *,
    processed_url: str,
    stored_original_url: str,
    original_url_index: int,
) -> bool:
    normalized_processed_url = _normalize_url_for_match(processed_url)
    for row in embed_rows:
        row_url = row[2]
        if (
            isinstance(row_url, str)
            and _normalize_url_for_match(row_url) == normalized_processed_url
        ):
            row[original_url_index] = stored_original_url
            return True

    return False


async def init_message_archive_schema() -> None:
    db = get_connection("default")
    schema = None
    if db.capabilities.dialect == "sqlite":
        schema = MESSAGE_ARCHIVE_SCHEMA
    elif db.capabilities.dialect == "postgres":
        schema = POSTGRES_MESSAGE_ARCHIVE_SCHEMA
    else:
        logger.warning("Message archive schema is only created for SQLite/PostgreSQL connections")
        return

    execute_script = getattr(db, "execute_script", None)
    if execute_script is not None:
        await execute_script(schema)
        return

    for statement in schema.split(";"):
        statement = statement.strip()
        if statement:
            await db.execute_query(f"{statement};")


async def archive_message(
    message: discord.Message,
    *,
    url_pairs: list[tuple[str, str]] | None = None,
    medias: list[Media] | None = None,
) -> None:
    try:
        db = get_connection("default")
        if db.capabilities.dialect == "sqlite":
            await _archive_sqlite_message(
                message, url_pairs=url_pairs or [], medias=medias or []
            )
        elif db.capabilities.dialect == "postgres":
            await _archive_postgres_message(
                message, url_pairs=url_pairs or [], medias=medias or []
            )
        else:
            return

    except Exception:
        logger.exception(
            f"Failed to archive message {message.id} in channel {message.channel.id}"
        )


async def archive_fixed_message_embeds(
    original_message: discord.Message,
    fixed_message: discord.Message,
    *,
    url_pairs: list[tuple[str, str]],
    downloaded_image_filenames: Mapping[str, str] | None = None,
) -> None:
    try:
        db = get_connection("default")
        if not fixed_message.embeds:
            logger.info(
                "Fixed message has no embeds yet: "
                f"original_message_id={original_message.id}, "
                f"fixed_message_id={fixed_message.id}, "
                f"content={fixed_message.content!r}, "
                f"url_pairs={url_pairs!r}"
            )
            return

        if db.capabilities.dialect == "sqlite":
            await _archive_sqlite_fixed_message_embeds(
                original_message,
                fixed_message,
                url_pairs=url_pairs,
                downloaded_image_filenames=downloaded_image_filenames or {},
            )
        elif db.capabilities.dialect == "postgres":
            await _archive_postgres_fixed_message_embeds(
                original_message,
                fixed_message,
                url_pairs=url_pairs,
                downloaded_image_filenames=downloaded_image_filenames or {},
            )
    except Exception:
        logger.exception(
            "Failed to archive fixed message embeds: "
            f"original_message_id={original_message.id}, fixed_message_id={fixed_message.id}"
        )


async def _archive_sqlite_message(
    message: discord.Message,
    *,
    url_pairs: list[tuple[str, str]],
    medias: list[Media],
) -> None:
    db = get_connection("default")
    message_id = str(message.id)
    timestamp = int(message.created_at.timestamp())
    embed_timestamp = message.created_at.isoformat()

    await db.execute_query(
        """
        INSERT OR REPLACE INTO "message"
            (channel_id, id, content, username, "timestamp")
        VALUES (?, ?, ?, ?, ?)
        """,
        [
            str(message.channel.id),
            message_id,
            message.content,
            message.author.display_name,
            timestamp,
        ],
    )

    existing_embed_rows = []
    if url_pairs or medias:
        existing_embed_rows = await db.execute_query_dict(
            """
            SELECT
                title, url, author_icon_url, author_name, author_url, description,
                footer_icon_url, footer_text, image_url, image_proxy_url, "timestamp",
                local_filename, orginal_url, is_downloaded
            FROM "embed"
            WHERE message_id = ?
            """,
            [message_id],
        )

    await db.execute_query('DELETE FROM "embed" WHERE message_id = ?', [message_id])
    await db.execute_query('DELETE FROM "attachment" WHERE message_id = ?', [message_id])

    attachment_rows = [
        [
            str(attachment.id),
            message_id,
            attachment.size,
            attachment.filename,
            attachment.url,
            int(attachment.ephemeral),
            0,
        ]
        for attachment in message.attachments
    ]
    if attachment_rows:
        await db.execute_many(
            """
            INSERT OR REPLACE INTO "attachment"
                (id, message_id, "size", filename, url, ephemeral, is_downloaded)
            VALUES (?, ?, ?, ?, ?, ?, ?)
            """,
            attachment_rows,
        )

    embed_rows: list[list[object | None]] = []
    for embed in message.embeds:
        timestamp_value = embed.timestamp.isoformat() if embed.timestamp else embed_timestamp
        embed_rows.append(
            [
                message_id,
                embed.title or "",
                embed.url or "",
                embed.author.icon_url,
                embed.author.name,
                embed.author.url,
                embed.description or "",
                embed.footer.icon_url,
                embed.footer.text,
                embed.image.url,
                embed.image.proxy_url,
                timestamp_value,
                None,
                None,
                0,
            ]
        )

    if existing_embed_rows:
        embed_rows = [
            [
                message_id,
                row["title"] or "",
                row["url"] or "",
                row["author_icon_url"],
                row["author_name"],
                row["author_url"],
                row["description"] or "",
                row["footer_icon_url"],
                row["footer_text"],
                row["image_url"],
                row["image_proxy_url"],
                row["timestamp"] or embed_timestamp,
                row["local_filename"],
                row["orginal_url"],
                row["is_downloaded"],
            ]
            for row in existing_embed_rows
        ]

    for original_url, processed_url in url_pairs:
        if _merge_processed_url(
            embed_rows,
            original_url=original_url,
            processed_url=processed_url,
            original_url_index=13,
        ):
            continue

        embed_rows.append(
            [
                message_id,
                "",
                processed_url,
                None,
                None,
                None,
                "",
                None,
                None,
                None,
                None,
                embed_timestamp,
                None,
                original_url,
                0,
            ]
        )

    for media in medias:
        local_filename = None if media.file is None else media.file.filename
        embed_rows.append(
            [
                message_id,
                "",
                media.url,
                None,
                None,
                None,
                "",
                None,
                None,
                media.url,
                None,
                embed_timestamp,
                local_filename,
                media.url,
                int(media.file is not None),
            ]
        )

    if embed_rows:
        await db.execute_many(
            """
            INSERT INTO "embed"
                (
                    message_id, title, url, author_icon_url, author_name, author_url,
                    description, footer_icon_url, footer_text, image_url, image_proxy_url,
                    "timestamp", local_filename, orginal_url, is_downloaded
                )
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            """,
            embed_rows,
        )


async def _archive_sqlite_fixed_message_embeds(
    original_message: discord.Message,
    fixed_message: discord.Message,
    *,
    url_pairs: list[tuple[str, str]],
    downloaded_image_filenames: Mapping[str, str],
) -> None:
    db = get_connection("default")
    message_id = str(original_message.id)
    timestamp = original_message.created_at.isoformat()

    embed_rows: list[list[object | None]] = []
    for embed in fixed_message.embeds:
        timestamp_value = embed.timestamp.isoformat() if embed.timestamp else timestamp
        image_url = embed.image.url
        local_filename = None if image_url is None else downloaded_image_filenames.get(image_url)
        embed_rows.append(
            [
                message_id,
                embed.title or "",
                embed.url or "",
                embed.author.icon_url,
                embed.author.name,
                embed.author.url,
                embed.description or "",
                embed.footer.icon_url,
                embed.footer.text,
                image_url,
                embed.image.proxy_url,
                timestamp_value,
                local_filename,
                None,
                int(local_filename is not None),
            ]
        )

    for original_url, processed_url in url_pairs:
        _set_original_url_for_processed_url(
            embed_rows,
            processed_url=processed_url,
            stored_original_url=original_url,
            original_url_index=13,
        )

    await db.execute_query('DELETE FROM "embed" WHERE message_id = ?', [message_id])
    await db.execute_many(
        """
        INSERT INTO "embed"
            (
                message_id, title, url, author_icon_url, author_name, author_url,
                description, footer_icon_url, footer_text, image_url, image_proxy_url,
                "timestamp", local_filename, orginal_url, is_downloaded
            )
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        """,
        embed_rows,
    )


async def _archive_postgres_message(
    message: discord.Message,
    *,
    url_pairs: list[tuple[str, str]],
    medias: list[Media],
) -> None:
    db = get_connection("default")
    message_id = int(message.id)
    created_at = _postgres_timestamp(message.created_at)

    await db.execute_query(
        """
        INSERT INTO "message"
            (id, channel_id, "content", username, "timestamp")
        VALUES ($1, $2, $3, $4, $5)
        ON CONFLICT (id) DO UPDATE SET
            channel_id = EXCLUDED.channel_id,
            "content" = EXCLUDED."content",
            username = EXCLUDED.username,
            "timestamp" = EXCLUDED."timestamp"
        """,
        [
            message_id,
            int(message.channel.id),
            _truncate(message.content, 1024),
            _truncate(message.author.display_name, 128),
            created_at,
        ],
    )

    existing_embed_rows = []
    if url_pairs or medias:
        existing_embed_rows = await db.execute_query_dict(
            """
            SELECT
                title, url, author_icon_url, author_name, author_url, description,
                footer_icon_url, footer_text, image_url, image_proxy_url, "timestamp",
                embed_timestamp, local_filename, orginal_url, is_downloaded
            FROM "embed"
            WHERE message_id = $1
            """,
            [message_id],
        )

    await db.execute_query('DELETE FROM "embed" WHERE message_id = $1', [message_id])
    await db.execute_query('DELETE FROM "attachment" WHERE message_id = $1', [message_id])

    attachment_rows = [
        [
            message_id,
            attachment.size,
            _truncate(attachment.filename, 512),
            _truncate(attachment.url, 512),
            int(attachment.ephemeral),
            False,
        ]
        for attachment in message.attachments
    ]
    if attachment_rows:
        await db.execute_many(
            """
            INSERT INTO "attachment"
                (message_id, "size", filename, url, ephemeral, is_downloaded)
            VALUES ($1, $2, $3, $4, $5, $6)
            """,
            attachment_rows,
        )

    embed_rows: list[list[object | None]] = []
    for embed in message.embeds:
        embed_rows.append(
            [
                message_id,
                _truncate(embed.title, 1024),
                _truncate(embed.url, 512),
                _truncate(embed.author.icon_url, 512),
                _truncate(embed.author.name, 128),
                _truncate(embed.author.url, 512),
                _truncate(embed.description, 512),
                _truncate(embed.footer.icon_url, 512),
                _truncate(embed.footer.text, 512),
                _truncate(embed.image.url, 512),
                _truncate(embed.image.proxy_url, 512),
                created_at,
                _postgres_timestamp(embed.timestamp),
                None,
                None,
                False,
            ]
        )

    if existing_embed_rows:
        embed_rows = [
            [
                message_id,
                row["title"],
                row["url"],
                row["author_icon_url"],
                row["author_name"],
                row["author_url"],
                row["description"],
                row["footer_icon_url"],
                row["footer_text"],
                row["image_url"],
                row["image_proxy_url"],
                row["timestamp"] or created_at,
                row["embed_timestamp"],
                row["local_filename"],
                row["orginal_url"],
                row["is_downloaded"],
            ]
            for row in existing_embed_rows
        ]

    for original_url, processed_url in url_pairs:
        if _merge_processed_url(
            embed_rows,
            original_url=original_url,
            processed_url=_truncate(processed_url, 512) or "",
            stored_original_url=_truncate(original_url, 512),
            original_url_index=14,
        ):
            continue

        embed_rows.append(
            [
                message_id,
                None,
                _truncate(processed_url, 512),
                None,
                None,
                None,
                None,
                None,
                None,
                None,
                None,
                created_at,
                None,
                None,
                _truncate(original_url, 512),
                False,
            ]
        )

    for media in medias:
        local_filename = None if media.file is None else media.file.filename
        embed_rows.append(
            [
                message_id,
                None,
                _truncate(media.url, 512),
                None,
                None,
                None,
                None,
                None,
                None,
                _truncate(media.url, 512),
                None,
                created_at,
                None,
                _truncate(local_filename, 512),
                _truncate(media.url, 512),
                media.file is not None,
            ]
        )

    if embed_rows:
        await db.execute_many(
            """
            INSERT INTO "embed"
                (
                    message_id, title, url, author_icon_url, author_name, author_url,
                    description, footer_icon_url, footer_text, image_url, image_proxy_url,
                    "timestamp", embed_timestamp, local_filename, orginal_url, is_downloaded
                )
            VALUES (
                $1, $2, $3, $4, $5, $6, $7, $8,
                $9, $10, $11, $12, $13, $14, $15, $16
            )
            """,
            embed_rows,
        )


async def _archive_postgres_fixed_message_embeds(
    original_message: discord.Message,
    fixed_message: discord.Message,
    *,
    url_pairs: list[tuple[str, str]],
    downloaded_image_filenames: Mapping[str, str],
) -> None:
    db = get_connection("default")
    message_id = int(original_message.id)
    created_at = _postgres_timestamp(original_message.created_at)

    embed_rows: list[list[object | None]] = []
    for embed in fixed_message.embeds:
        image_url = embed.image.url
        local_filename = None if image_url is None else downloaded_image_filenames.get(image_url)
        embed_rows.append(
            [
                message_id,
                _truncate(embed.title, 1024),
                _truncate(embed.url, 512),
                _truncate(embed.author.icon_url, 512),
                _truncate(embed.author.name, 128),
                _truncate(embed.author.url, 512),
                _truncate(embed.description, 512),
                _truncate(embed.footer.icon_url, 512),
                _truncate(embed.footer.text, 512),
                _truncate(image_url, 512),
                _truncate(embed.image.proxy_url, 512),
                created_at,
                _postgres_timestamp(embed.timestamp),
                _truncate(local_filename, 512),
                None,
                local_filename is not None,
            ]
        )

    for original_url, processed_url in url_pairs:
        _set_original_url_for_processed_url(
            embed_rows,
            processed_url=processed_url,
            stored_original_url=_truncate(original_url, 512) or "",
            original_url_index=14,
        )

    await db.execute_query('DELETE FROM "embed" WHERE message_id = $1', [message_id])
    await db.execute_many(
        """
        INSERT INTO "embed"
            (
                message_id, title, url, author_icon_url, author_name, author_url,
                description, footer_icon_url, footer_text, image_url, image_proxy_url,
                "timestamp", embed_timestamp, local_filename, orginal_url, is_downloaded
            )
        VALUES (
            $1, $2, $3, $4, $5, $6, $7, $8,
            $9, $10, $11, $12, $13, $14, $15, $16
        )
        """,
        embed_rows,
    )
